from Tkinter import *
import pygame
import winsound
import random

window = Tk()
window.geometry("1150x425")
colors = ['blue', 'red', 'pink', 'royal blue', 'green', 'orange', 'cyan', 'purple', 'magenta', 'hot pink', 'gold',
          'yellow', 'aqua', 'chartreuse']

pygame.mixer.pre_init(frequency=22050, size=-16, channels=40, buffer=256)
pygame.mixer.init()
sound1 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Snare1.wav')
sound2 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Snare2.wav')
sound3 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Snare3.wav')
sound4 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Snare4.wav')
sound5 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Snare5.wav')
sound6 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Snare6.wav')
sound7 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Snare7,.wav')
sound8 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Snare8.wav')
sound9 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Snare9.wav')
sound10 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Snare10.wav')
sound11 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Kick1.wav')
sound12 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Kick2.wav')
sound13 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Kick3.wav')
sound14 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Kick4.wav')
sound15 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Kick5.wav')
sound16 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Kick6.wav')
sound17 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Kick7.wav')
sound18 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Kick8.wav')
sound19 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Kick9.wav')
sound20 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Kick10.wav')
sound21 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Ride-Cymbal1.wav')
sound22 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Ride-Cymbal2.wav')
sound23 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Ride-Cymbal3.wav')
sound24 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Ride-Cymbal4.wav')
sound25 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Ride-Cymbal5.wav')
sound26 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Ride-Cymbal6.wav')
sound27 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Ride-Cymbal7.wav')
sound28 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Ride-Cymbal8.wav')
sound29 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Ride-Cymbal9.wav')
sound30 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Ride-Cymbal10.wav')
sound31 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Hi-hat1.wav')
sound32 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Hi-hat2.wav')
sound33 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Hi-hat3.wav')
sound34 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Hi-hat4.wav')
sound35 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Hi-hat5.wav')
sound36 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Hi-hat6.wav')
sound37 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Hi-hat7.wav')
sound38 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Hi-hat8.wav')
sound39 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Hi-hat9.wav')
sound40 = pygame.mixer.Sound('C:\Users\Vincent\PycharmProjects\CST205\Project3\Sounds\Hi-hat10.wav')

chan1 =pygame.mixer.Channel(0)
chan1.queue(sound1)
chan2 =pygame.mixer.Channel(1)
chan2.queue(sound2)
chan3 =pygame.mixer.Channel(2)
chan3.queue(sound3)
chan4 =pygame.mixer.Channel(3)
chan4.queue(sound4)

#create so the close button will end the program and close the window.
def quit():
    window.destroy()

'''
instruments = ['kick', 'snare', 'pit bull', 'hi-hat']


snare = ['http://har-bal.com/reference/Percussion/fmcr2.wav', 'http://www.denhaku.com/r_box/rx11/hi_tune_1.wav'
                                                              'http://files.chatnfiles.com/10000_sounds_and_songs/WAV/SNARE_3.WAV',
         'http://www.nebo.edu/learning_resources/ppt/sounds/baboom.wav'
         'ftp://ftp.lysator.liu.se/pub/awe32/wav/808Snare.wav', 'http://www.denhaku.com/r_box/linn/sd1.wav',
         'http://www.barryrudolph.com/mix/breverb/wav/6.wav', 'http://www.denhaku.com/r_box/sr16/sr16sd/chromesn.wav',
         'http://www.daimi.au.dk/~pmn/spf02/CDROM/pr4/sound/amp300_16bit_mono/snare/snare1_4.wav',
         'http://home1.swipnet.se/~w-33956/ifsd2.wav']

kick = ['http://www.denhaku.com/r_box/sr16/sr16bd/dbl%15head.wav', 'http://www.denhaku.com/r_box/rx11/bd_md_1.wav',
        'http://www.zone0ne.com/bassics/wav/bassdrum.wav',
        'ftp://sunsite.univie.ac.at/pub/sound/csound/utilities/pc/midi2cs/21550/bd1_s48k.wav',
        'http://soundcavern.free.fr/kits/Act%15Bass%15Drum.wav',
        'http://veikko.pp.fi/Testi1/SAMPLEJA_PLUGAREITA/fl5_samlpleja_synia/Vintage/hhd1kck10.wav',
        'http://work.colum.edu/~nlinscheid/sound-library/sdif-tests/bassdrum.aiff',
        'http://soundcavern.free.fr/kick/kick009.wav',
        'http://www.imjohn.com/PresonusJensenXfrmrs/sounds/16-44.1/Channel%15Indicator.wav',
        'http://cstrike.csmegagaming.com/sound/misc/pb2.wav', ]

pitbull = ['http://free-sounds.net/sound-files/animal-sounds/dog-sounds/DOG15.WAV',
           'http://www.presepioelettronico.it/downloads/audio/files/cani.wav',
           'http://www.gkgraphics.com/download/sounds/wav/mono/Bark.wav',
           'http://www.gravomaster.com/alarm/sounds/Dog_Bark_02.wav',
           'http://www.nyanmilla.net/wav/dog00.wav',
           'http://www-cs-students.stanford.edu/~echawkes/Snakebite/Bark.aiff',
           'http://www.threecaster.com/wavy/BarkingP.WAV', 'http://www.wavlist.com/soundfx/001/dog-bark5.wav',
           'http://www.nifter.com/sound_effects/animals_sounds/dog_barking_NifterDotCom.wav',
           'http://www.mcello63.com/suonerie_varie/Latrato.mp3', ]

hihat = ['http://www.marksmart.net/gearhack/jazzpedalboard/Footprints4BarLoop.wav',
         'http://machines.hyperreal.org/manufacturers/Casio/RZ-1/samples/tmp/casio-rz1/HCRZ.WAV',
         'http://www.denhaku.com/r_box/tr707/closed.wav', 'http://bigsamples.free.fr/d_kit/hithat/hat_2.wav',
         'http://bigsamples.free.fr/d_kit/hithat/hh1.wav', 'http://cd.textfiles.com/sigserieswin/SOUNDS/WAV/HIHAT.WAV',
         'http://www.vrsound.com/vrwaves/vrsound_hat2.wav',
         'http://www.whitenote.dk/Download%15Frame/Whitenote%15Sampels/Aids%15virus/Hi-hat%152.wav',
         'http://tipiwiki.free.fr/snd/TimbaleCourte.wav',
         'http://www.americanmusical.com/ItemFiles/MP3/PST5_14_medium_hats_chick.mp3', ]

frame = Frame(root)
Grid.rowconfigure(root, 0, weight=1)
Grid.columnconfigure(root, 0, weight=1)
frame.grid(row=0, column=0, sticky=N + S + E + W)
grid = Frame(frame)
grid.grid(sticky=N + S + E + W, column=0, row=7, columnspan=2)
Grid.rowconfigure(frame, 0, weight=1)
Grid.columnconfigure(frame, 0, weight=1)


for x in range(10):
    for y in range(4):
        btn = Button(frame, text = "%s %d" % (instruments[y], x + 1), bg="white",
                     activebackround = random.choice(colors),
                     lambda: winsound.PlaySound(sounds[y], winsound.SND_ASYNC))

        btn = Button(frame, text=list[y] + " " + str(x + 1), bg="white", activebackground=random.choice(colors))
        btn.bind("<Enter>", lambda event, b=btn: b.configure(bg=random.choice(colors)))
        btn.bind("<Leave>", lambda event, b=btn: b.configure(bg=random.choice(colors)))
        btn.bind("<Button-1>", lambda event, b=btn: b.configure(bg=random.choice(colors)))
        btn.bind("keys", lambda event, b=btn: b.configure(bg=random.choice(colors)))
        btn.grid(column=x, row=y, sticky=N + S + E + W)

for x in range(10):
    Grid.columnconfigure(frame, x, weight=1)

for y in range(5):
    Grid.rowconfigure(frame, y, weight=1)
'''

#Declaring Buttons
button1 = Button(window, text="Snare 1", bg="black",fg="white", activebackground=random.choice(colors), height=5, width=15)
button2 = Button(window, text="Snare 2", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button3 = Button(window, text="Snare 3", bg="black",fg="white", activebackground=random.choice(colors), height=5, width=15)
button4 = Button(window, text="Snare 4", bg="black",fg="white", activebackground=random.choice(colors), height=5, width=15)
button5 = Button(window, text="Snare 5", bg="black",fg="white", activebackground=random.choice(colors), height=5, width=15)
button6 = Button(window, text="Snare 6", bg="black",fg="white", activebackground=random.choice(colors),  height=5, width=15)
button7 = Button(window, text="Snare 7", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button8 = Button(window, text="Snare 8", bg="black",fg="white", activebackground=random.choice(colors), height=5, width=15)
button9 = Button(window, text="Snare 9", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button10 = Button(window, text="Snare 10", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button11 = Button(window, text="Kick 1", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button12 = Button(window, text="Kick 2", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button13 = Button(window, text="Kick 3", bg="black",fg="white", activebackground=random.choice(colors), height=5, width=15)
button14 = Button(window, text="Kick 4", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button15 = Button(window, text="Kick 5", bg="black",fg="white", activebackground=random.choice(colors), height=5, width=15)
button16 = Button(window, text="Kick 6", bg="black",fg="white", activebackground=random.choice(colors), height=5, width=15)
button17 = Button(window, text="Kick 7", bg="black",fg="white", activebackground=random.choice(colors), height=5, width=15)
button18 = Button(window, text="Kick 8", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button19 = Button(window, text="Kick 9", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button20 = Button(window, text="Kick 10", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button21 = Button(window, text="Ride-Cymbal 1", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=15)
button22 = Button(window, text="Ride-Cymbal 2", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=15)
button23 = Button(window, text="Ride-Cymbal 3", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=15)
button24 = Button(window, text="Ride-Cymbal 4", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=15)
button25 = Button(window, text="Ride-Cymbal 5", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=15)
button26 = Button(window, text="Ride-Cymbal 6", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=15)
button27 = Button(window, text="Ride-Cymbal 7", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=15)
button28 = Button(window, text="Ride-Cymbal 8", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=15)
button29 = Button(window, text="Ride-Cymbal 9", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=15)
button30 = Button(window, text="Ride-Cymbal 10", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=15)
button31 = Button(window, text="Hi-hat 1", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button32 = Button(window, text="Hi-hat 2", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button33 = Button(window, text="Hi-hat 3", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button34 = Button(window, text="Hi-hat 4", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button35 = Button(window, text="Hi-hat 5", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button36 = Button(window, text="Hi-hat 6", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button37 = Button(window, text="Hi-hat 7", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button38 = Button(window, text="Hi-hat 8", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button39 = Button(window, text="Hi-hat 9", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
button40 = Button(window, text="Hi-hat 10", bg="black", fg="white", activebackground=random.choice(colors), height=5, width=15)
buttonClose = Button(window, text="Close", bg="black", fg="white", command=quit, activebackground=random.choice(colors), height=5, width=165)
'''
buttonPlay=Button(window,text="Play", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=81)
buttonClear=Button(window,text="Clear", bg="black", fg="white",activebackground=random.choice(colors), height=5, width=81)
'''

# binding Hover Function
button1.bind("<Enter>", lambda event, b=button1: b.configure(bg=random.choice(colors)) )
button1.bind("<Leave>", lambda event, b=button1: b.configure(bg="black"))
button2.bind("<Enter>", lambda event, b=button2: b.configure(bg=random.choice(colors)))
button2.bind("<Leave>", lambda event, b=button2: b.configure(bg="black"))
button3.bind("<Enter>", lambda event, b=button3: b.configure(bg=random.choice(colors)))
button3.bind("<Leave>", lambda event, b=button3: b.configure(bg="black"))
button4.bind("<Enter>", lambda event, b=button4: b.configure(bg=random.choice(colors)))
button4.bind("<Leave>", lambda event, b=button4: b.configure(bg="black"))
button5.bind("<Enter>", lambda event, b=button5: b.configure(bg=random.choice(colors)))
button5.bind("<Leave>", lambda event, b=button5: b.configure(bg="black"))
button6.bind("<Enter>", lambda event, b=button6: b.configure(bg=random.choice(colors)))
button6.bind("<Leave>", lambda event, b=button6: b.configure(bg="black"))
button7.bind("<Enter>", lambda event, b=button7: b.configure(bg=random.choice(colors)))
button7.bind("<Leave>", lambda event, b=button7: b.configure(bg="black"))
button8.bind("<Enter>", lambda event, b=button8: b.configure(bg=random.choice(colors)))
button8.bind("<Leave>", lambda event, b=button8: b.configure(bg="black"))
button9.bind("<Enter>", lambda event, b=button9: b.configure(bg=random.choice(colors)))
button9.bind("<Leave>", lambda event, b=button9: b.configure(bg="black"))
button10.bind("<Enter>", lambda event, b=button10: b.configure(bg=random.choice(colors)))
button10.bind("<Leave>", lambda event, b=button10: b.configure(bg="black"))
button11.bind("<Enter>", lambda event, b=button11: b.configure(bg=random.choice(colors)))
button11.bind("<Leave>", lambda event, b=button11: b.configure(bg="black"))
button12.bind("<Enter>", lambda event, b=button12: b.configure(bg=random.choice(colors)))
button12.bind("<Leave>", lambda event, b=button12: b.configure(bg="black"))
button13.bind("<Enter>", lambda event, b=button13: b.configure(bg=random.choice(colors)))
button13.bind("<Leave>", lambda event, b=button13: b.configure(bg="black"))
button14.bind("<Enter>", lambda event, b=button14: b.configure(bg=random.choice(colors)))
button14.bind("<Leave>", lambda event, b=button14: b.configure(bg="black"))
button15.bind("<Enter>", lambda event, b=button15: b.configure(bg=random.choice(colors)))
button15.bind("<Leave>", lambda event, b=button15: b.configure(bg="black"))
button16.bind("<Enter>", lambda event, b=button16: b.configure(bg=random.choice(colors)))
button16.bind("<Leave>", lambda event, b=button16: b.configure(bg="black"))
button17.bind("<Enter>", lambda event, b=button17: b.configure(bg=random.choice(colors)))
button17.bind("<Leave>", lambda event, b=button17: b.configure(bg="black"))
button18.bind("<Enter>", lambda event, b=button18: b.configure(bg=random.choice(colors)))
button18.bind("<Leave>", lambda event, b=button18: b.configure(bg="black"))
button19.bind("<Enter>", lambda event, b=button19: b.configure(bg=random.choice(colors)))
button19.bind("<Leave>", lambda event, b=button19: b.configure(bg="black"))
button20.bind("<Enter>", lambda event, b=button20: b.configure(bg=random.choice(colors)))
button20.bind("<Leave>", lambda event, b=button20: b.configure(bg="black"))
button21.bind("<Enter>", lambda event, b=button21: b.configure(bg=random.choice(colors)))
button21.bind("<Leave>", lambda event, b=button21: b.configure(bg="black"))
button22.bind("<Enter>", lambda event, b=button22: b.configure(bg=random.choice(colors)))
button22.bind("<Leave>", lambda event, b=button22: b.configure(bg="black"))
button23.bind("<Enter>", lambda event, b=button23: b.configure(bg=random.choice(colors)))
button23.bind("<Leave>", lambda event, b=button23: b.configure(bg="black"))
button24.bind("<Enter>", lambda event, b=button24: b.configure(bg=random.choice(colors)))
button24.bind("<Leave>", lambda event, b=button24: b.configure(bg="black"))
button25.bind("<Enter>", lambda event, b=button25: b.configure(bg=random.choice(colors)))
button25.bind("<Leave>", lambda event, b=button25: b.configure(bg="black"))
button26.bind("<Enter>", lambda event, b=button26: b.configure(bg=random.choice(colors)))
button26.bind("<Leave>", lambda event, b=button26: b.configure(bg="black"))
button27.bind("<Enter>", lambda event, b=button27: b.configure(bg=random.choice(colors)))
button27.bind("<Leave>", lambda event, b=button27: b.configure(bg="black"))
button28.bind("<Enter>", lambda event, b=button28: b.configure(bg=random.choice(colors)))
button28.bind("<Leave>", lambda event, b=button28: b.configure(bg="black"))
button29.bind("<Enter>", lambda event, b=button29: b.configure(bg=random.choice(colors)))
button29.bind("<Leave>", lambda event, b=button29: b.configure(bg="black"))
button30.bind("<Enter>", lambda event, b=button30: b.configure(bg=random.choice(colors)))
button30.bind("<Leave>", lambda event, b=button30: b.configure(bg="black"))
button31.bind("<Enter>", lambda event, b=button31: b.configure(bg=random.choice(colors)))
button31.bind("<Leave>", lambda event, b=button31: b.configure(bg="black"))
button32.bind("<Enter>", lambda event, b=button32: b.configure(bg=random.choice(colors)))
button32.bind("<Leave>", lambda event, b=button32: b.configure(bg="black"))
button33.bind("<Enter>", lambda event, b=button33: b.configure(bg=random.choice(colors)))
button33.bind("<Leave>", lambda event, b=button33: b.configure(bg="black"))
button34.bind("<Enter>", lambda event, b=button34: b.configure(bg=random.choice(colors)))
button34.bind("<Leave>", lambda event, b=button34: b.configure(bg="black"))
button35.bind("<Enter>", lambda event, b=button35: b.configure(bg=random.choice(colors)))
button35.bind("<Leave>", lambda event, b=button35: b.configure(bg="black"))
button36.bind("<Enter>", lambda event, b=button36: b.configure(bg=random.choice(colors)))
button36.bind("<Leave>", lambda event, b=button36: b.configure(bg="black"))
button37.bind("<Enter>", lambda event, b=button37: b.configure(bg=random.choice(colors)))
button37.bind("<Leave>", lambda event, b=button37: b.configure(bg="black"))
button38.bind("<Enter>", lambda event, b=button38: b.configure(bg=random.choice(colors)))
button38.bind("<Leave>", lambda event, b=button38: b.configure(bg="black"))
button39.bind("<Enter>", lambda event, b=button39: b.configure(bg=random.choice(colors)))
button39.bind("<Leave>", lambda event, b=button39: b.configure(bg="black"))
button40.bind("<Enter>", lambda event, b=button40: b.configure(bg=random.choice(colors)))
button40.bind("<Leave>", lambda event, b=button40: b.configure(bg="black"))
buttonClose.bind("<Enter>"), lambda event, b=buttonClose: b.configure(bg=random.choice(colors))
buttonClose.bind("<Leave>"), lambda event, b=buttonClose: b.configure(bg="black")

'''
buttonPlay.bind("<Enter>", lambda event, b=buttonPlay: b.configure(bg=random.choice(colors)))
buttonPlay.bind("<Leave>", lambda event, b=buttonPlay: b.configure(bg="black"))
buttonClear.bind("<Enter>", lambda event, b=buttonClear: b.configure(bg=random.choice(colors)))
buttonClear.bind("<Leave>", lambda event, b=buttonClear: b.configure(bg="black"))
'''
#function for adding sounds
button1.bind("<Button-1>", lambda event: sound1.play())
button1.bind("<Button-3>", lambda event, b=button1: b.configure(bg="white"))
window.bind('q', lambda e: sound1.play())
button2.bind("<Button-1>", lambda event: sound2.play())
button2.bind("<Button-3>", lambda event, b=button2: b.configure(bg="white"))
window.bind('w', lambda e: sound2.play())
button3.bind("<Button-1>", lambda event: sound3.play())
button3.bind("<Button-3>", lambda event, b=button3: b.configure(bg="white"))
window.bind('e', lambda e: sound3.play())
button4.bind("<Button-1>", lambda event: sound4.play())
button4.bind("<Button-3>", lambda event, b=button4: b.configure(bg="white"))
window.bind('r', lambda e: sound4.play())
button5.bind("<Button-1>", lambda event: sound5.play())
button5.bind("<Button-3>", lambda event, b=button5: b.configure(bg="white"))
window.bind('t', lambda e: sound5.play())
button6.bind("<Button-1>", lambda event: sound6.play())
button6.bind("<Button-3>", lambda event, b=button6: b.configure(bg="white"))
window.bind('y', lambda e: sound6.play())
button7.bind("<Button-1>", lambda event: sound7.play())
button7.bind("<Button-3>", lambda event, b=button7: b.configure(bg="white"))
window.bind('u', lambda e: sound7.play())
button8.bind("<Button-1>", lambda event: sound8.play())
button8.bind("<Button-3>", lambda event, b=button8: b.configure(bg="white"))
window.bind('i', lambda e: sound8.play())
button9.bind("<Button-1>", lambda event: sound9.play())
button9.bind("<Button-3>", lambda event, b=button9: b.configure(bg="white"))
window.bind('o', lambda e: sound9.play())
button10.bind("<Button-1>", lambda event: sound10.play())
button10.bind("<Button-3>", lambda event, b=button10: b.configure(bg="white"))
window.bind('p', lambda e: sound10.play())
button11.bind("<Button-1>", lambda event: sound11.play())
button11.bind("<Button-3>", lambda event, b=button11: b.configure(bg="white"))
window.bind('a', lambda e: sound11.play())
button12.bind("<Button-1>", lambda event: sound12.play())
button12.bind("<Button-3>", lambda event, b=button12: b.configure(bg="white"))
window.bind('s', lambda e: sound12.play())
button13.bind("<Button-1>", lambda event: sound13.play())
button13.bind("<Button-3>", lambda event, b=button13: b.configure(bg="white"))
window.bind('d', lambda e: sound13.play())
button14.bind("<Button-1>", lambda event: sound14.play())
button14.bind("<Button-3>", lambda event, b=button14: b.configure(bg="white"))
window.bind('f', lambda e: sound14.play())
button15.bind("<Button-1>", lambda event: sound15.play())
button15.bind("<Button-3>", lambda event, b=button15: b.configure(bg="white"))
window.bind('g', lambda e: sound15.play())
button16.bind("<Button-1>", lambda event: sound16.play())
button16.bind("<Button-3>", lambda event, b=button16: b.configure(bg="white"))
window.bind('h', lambda e: sound16.play())
button17.bind("<Button-1>", lambda event: sound17.play())
button17.bind("<Button-3>", lambda event, b=button17: b.configure(bg="white"))
window.bind('j', lambda e: sound17.play())
button18.bind("<Button-1>", lambda event: sound18.play())
button18.bind("<Button-3>", lambda event, b=button18: b.configure(bg="white"))
window.bind('k', lambda e: sound18.play())
button19.bind("<Button-1>", lambda event: sound19.play())
button19.bind("<Button-3>", lambda event, b=button19: b.configure(bg="white"))
window.bind('l', lambda e: sound19.play())
button20.bind("<Button-1>", lambda event: sound20.play())
button20.bind("<Button-3>", lambda event, b=button20: b.configure(bg="white"))
window.bind('z', lambda e: sound20.play())
button21.bind("<Button-1>", lambda event: sound21.play())
button21.bind("<Button-3>", lambda event, b=button21: b.configure(bg="white"))
window.bind('x', lambda e: sound21.play())
button22.bind("<Button-1>", lambda event: sound22.play())
button22.bind("<Button-3>", lambda event, b=button22: b.configure(bg="white"))
window.bind('c', lambda e: sound22.play())
button23.bind("<Button-1>", lambda event: sound23.play())
button23.bind("<Button-3>", lambda event, b=button23: b.configure(bg="white"))
window.bind('v', lambda e: sound23.play())
button24.bind("<Button-1>", lambda event: sound24.play())
button24.bind("<Button-3>", lambda event, b=button24: b.configure(bg="white"))
window.bind('b', lambda e: sound24.play())
button25.bind("<Button-1>", lambda event: sound25.play())
button25.bind("<Button-3>", lambda event, b=button25: b.configure(bg="white"))
window.bind('n', lambda e: sound25.play())
button26.bind("<Button-1>", lambda event: sound26.play())
button26.bind("<Button-3>", lambda event, b=button26: b.configure(bg="white"))
window.bind('m', lambda e: sound26.play())
button27.bind("<Button-1>", lambda event: sound27.play())
button27.bind("<Button-3>", lambda event, b=button27: b.configure(bg="white"))
window.bind('1', lambda e: sound27.play())
button28.bind("<Button-1>", lambda event: sound28.play())
button28.bind("<Button-3>", lambda event, b=button28: b.configure(bg="white"))
window.bind('2', lambda e: sound28.play())
button29.bind("<Button-1>", lambda event: sound29.play())
button29.bind("<Button-3>", lambda event, b=button29: b.configure(bg="white"))
window.bind('3', lambda e: sound29.play())
button30.bind("<Button-1>", lambda event: sound30.play())
button30.bind("<Button-3>", lambda event, b=button30: b.configure(bg="white"))
window.bind('4', lambda e: sound30.play())
button31.bind("<Button-1>", lambda event: sound31.play())
button31.bind("<Button-3>", lambda event, b=button31: b.configure(bg="white"))
window.bind('5', lambda e: sound31.play())
button32.bind("<Button-1>", lambda event: sound32.play())
button32.bind("<Button-3>", lambda event, b=button32: b.configure(bg="white"))
window.bind('6', lambda e: sound32.play())
button33.bind("<Button-1>", lambda event: sound33.play())
button33.bind("<Button-3>", lambda event, b=button33: b.configure(bg="white"))
window.bind('7', lambda e: sound33.play())
button34.bind("<Button-1>", lambda event: sound34.play())
button34.bind("<Button-3>", lambda event, b=button34: b.configure(bg="white"))
window.bind('8', lambda e: sound34.play())
button35.bind("<Button-1>", lambda event: sound35.play())
button35.bind("<Button-3>", lambda event, b=button35: b.configure(bg="white"))
window.bind('9', lambda e: sound35.play())
button36.bind("<Button-1>", lambda event: sound36.play())
button36.bind("<Button-3>", lambda event, b=button36: b.configure(bg="white"))
window.bind('0', lambda e: sound36.play())
button37.bind("<Button-1>", lambda event: sound37.play())
button37.bind("<Button-3>", lambda event, b=button37: b.configure(bg="white"))
window.bind('+', lambda e: sound37.play())
button38.bind("<Button-1>", lambda event: sound38.play())
button38.bind("<Button-3>", lambda event, b=button38: b.configure(bg="white"))
window.bind('-', lambda e: sound38.play())
button39.bind("<Button-1>", lambda event: sound39.play())
button39.bind("<Button-3>", lambda event, b=button39: b.configure(bg="white"))
window.bind('*', lambda e: sound39.play())
button40.bind("<Button-1>", lambda event: sound40.play())
button40.bind("<Button-3>", lambda event, b=button40: b.configure(bg="white"))
window.bind('`', lambda e: sound40.play())
buttonClose.bind("<Button-1>", lambda event, b=buttonClose: b.configure(bg=random.choice(colors)))
buttonClose.bind("<Button-3>", lambda event, b=buttonClose: b.configure(bg="white"))

'''buttonPlay.bind("<Button-1>", lambda event, b=buttonPlay: b.configure(bg=random.choice(colors)))
buttonPlay.bind("<Button-3>", lambda event, b=buttonPlay: b.configure(bg="white"))
buttonClear.bind("<Button-1>", lambda event, b=buttonClear: b.configure(bg=random.choice(colors)))
buttonClear.bind("<Button-3>", lambda event, b=buttonClear: b.configure(bg="white"))
'''

#Laying out the grid
button1.grid(row=0, column=0)
button2.grid(row=0, column=1)
button3.grid(row=0, column=2)
button4.grid(row=0, column=3)
button5.grid(row=0, column=4)
button6.grid(row=0, column=5)
button7.grid(row=0, column=6)
button8.grid(row=0, column=7)
button9.grid(row=0, column=8)
button10.grid(row=0, column=9)
button11.grid(row=1, column=0)
button12.grid(row=1, column=1)
button13.grid(row=1, column=2)
button14.grid(row=1, column=3)
button15.grid(row=1, column=4)
button16.grid(row=1, column=5)
button17.grid(row=1, column=6)
button18.grid(row=1, column=7)
button19.grid(row=1, column=8)
button20.grid(row=1, column=9)
button21.grid(row=2, column=0)
button22.grid(row=2, column=1)
button23.grid(row=2, column=2)
button24.grid(row=2, column=3)
button25.grid(row=2, column=4)
button26.grid(row=2, column=5)
button27.grid(row=2, column=6)
button28.grid(row=2, column=7)
button29.grid(row=2, column=8)
button30.grid(row=2, column=9)
button31.grid(row=3, column=0)
button32.grid(row=3, column=1)
button33.grid(row=3, column=2)
button34.grid(row=3, column=3)
button35.grid(row=3, column=4)
button36.grid(row=3, column=5)
button37.grid(row=3, column=6)
button38.grid(row=3, column=7)
button39.grid(row=3, column=8)
button40.grid(row=3, column=9)
buttonClose.grid(row=4,column=0, columnspan=10)

'''buttonPlay.grid(row=4,column=0,columnspan=5)
buttonClear.grid(row=4, column=5,columnspan=5)
'''

window.mainloop()